// js/data.js - Pusat Data Materi TJKT
const materiList = [
  { title: "1. Pengertian TJKT", badge: "Kelas 10" },
  { title: "2. Sejarah Jaringan Komputer", badge: "Kelas 10" },
  { title: "3. Jenis Jaringan Komputer", badge: "Kelas 10" },
  { title: "4. Topologi Jaringan Komputer", badge: "Kelas 10" },
  { title: "5. Perangkat Keras Jaringan", badge: "Kelas 10" },
  { title: "6. Media Transmisi & Kabel Jaringan", badge: "Kelas 10" },
  { title: "7. Pengalamatan IP (IP Address)", badge: "Kelas 10" },
  { title: "8. Proses Bisnis TJKT & K3LH", badge: "Kelas 10" },
  { title: "9. Perakitan Komputer & Hardware", badge: "Kelas 10" },
  { title: "10. Instalasi Sistem Operasi", badge: "Kelas 10" },
  { title: "11. Jaringan Dasar & Kabel", badge: "Kelas 10" },
  { title: "12. Alat Ukur & Pemeliharaan TJKT", badge: "Kelas 10" },
  { title: "13. Subnetting Dasar", badge: "Kelas 11" },
  { title: "14. Model Referensi OSI Layer", badge: "Kelas 11" },
  { title: "15. Protocol Suite TCP/IP", badge: "Kelas 11" },
  { title: "16. Konsep & Jenis Routing", badge: "Kelas 11" },
  { title: "17. Switching & Virtual LAN (VLAN)", badge: "Kelas 11" },
  { title: "18. Administrasi Infrastruktur Jaringan (AIJ)", badge: "Kelas 11" },
  { title: "19. Administrasi Sistem Jaringan (ASJ)", badge: "Kelas 11" },
  { title: "20. Teknologi Jaringan Berbasis Luas (WAN)", badge: "Kelas 11" },
  { title: "21. Keamanan Jaringan & Cyber Security", badge: "Kelas 11" },
  { title: "22. Firewall & Keamanan Jaringan", badge: "Kelas 12" },
  { title: "23. Server & Layanan Jaringan", badge: "Kelas 12" },
  { title: "24. Virtualisasi System & Server", badge: "Kelas 12" },
  { title: "25. Cloud Computing (Komputasi Awan)", badge: "Kelas 12" },
  { title: "26. AIJ Lanjutan & Bandwidth Management", badge: "Kelas 12" },
  { title: "27. ASJ Lanjutan & Troubleshooting", badge: "Kelas 12" },
  { title: "28. Teknologi Layanan Jaringan (VoIP & Fiber Optic)", badge: "Kelas 12" },
  { title: "29. Keamanan Server & Keamanan Siber", badge: "Kelas 12" },
  { title: "30. Produk Kreatif & Kewirausahaan (PKK)", badge: "Kelas 12" }
];